#!/bin/bash

interval=$1
file=$2
url=$3
username=$4
password=$5

cat /dev/null > $file

watches cluster_stats \
  -d -1 -i $interval \
  -sl \
  --url=$url \
  -f nodes.jvm.mem -f timestamp \
  >> $file
